In [50]:
import pandas
import json

In [76]:
pandas.read_csv("./LMS-DataStuff/pg_catalog.csv")

,Text#,Type,Issued,Title,Language,Authors,Subjects,LoCC,Bookshelves
0,1,Text,1971-12-01,The Declaration of Independence of the United ...,en,"Jefferson, Thomas, 1743-1826","United States -- History -- Revolution, 1775-1...",E201; JK,Politics; American Revolutionary War; United S...
1,2,Text,1972-12-01,The United States Bill of Rights\r\nThe Ten Or...,en,United States,Civil rights -- United States -- Sources; Unit...,JK; KF,Politics; American Revolutionary War; United S...
2,3,Text,1973-11-01,John F. Kennedy's Inaugural Address,en,"Kennedy, John F. (John Fitzgerald), 1917-1963",United States -- Foreign relations -- 1961-196...,E838,Browsing: History - American; Browsing: Politics
3,4,Text,1973-11-01,Lincoln's Gettysburg Address\r\nGiven November...,en,"Lincoln, Abraham, 1809-1865",Consecration of cemeteries -- Pennsylvania -- ...,E456,US Civil War; Browsing: History - American; Br...
4,5,Text,1975-12-01,The United States Constitution,en,United States,United States -- Politics and government -- 17...,JK; KF,United States; Politics; American Revolutionar...
...,...,...,...,...,...,...,...,...,...
76130,76310,Text,2025-06-15,Cindrulino,eo,"Milho, L.",NaN,NaN,NaN
76131,76311,Text,2025-06-15,The book of the cat,en,"Simpson, Frances",NaN,NaN,NaN
76132,76312,Text,2025-06-15,Viimeinen tsaaritar,fi,"Poljakov, V.",NaN,NaN,NaN
76133,76313,Text,2025-06-15,Voimatonta väkeä,fi,"Malmberg, Aino, 1865-1933",NaN,NaN,NaN
76134,76314,Text,2025-06-15,Genius rewarded,en,"Scott, John A.",NaN,NaN,NaN

In [55]:
pandas.read_csv("LMS-DataStuff/tcc_ceds_music.csv")

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,0,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.000000
1,4,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.000000
2,6,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.000000
3,10,pérez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.000000
4,12,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28367,82447,mack 10,10 million ways,2019,hip hop,cause fuck leave scar tick tock clock come kno...,78,0.001350,0.001350,0.001350,...,0.065664,0.001350,0.889527,0.759711,0.062549,0.000000,0.751649,0.695686,obscene,0.014286
28368,82448,m.o.p.,ante up (robbin hoodz theory),2019,hip hop,minks things chain ring braclets yap fame come...,67,0.001284,0.001284,0.035338,...,0.001284,0.001284,0.662082,0.789580,0.004607,0.000002,0.922712,0.797791,obscene,0.014286
28369,82449,nine,whutcha want?,2019,hip hop,get ban get ban stick crack relax plan attack ...,77,0.001504,0.154302,0.168988,...,0.001504,0.001504,0.663165,0.726970,0.104417,0.000001,0.838211,0.767761,obscene,0.014286
28370,82450,will smith,switch,2019,hip hop,check check yeah yeah hear thing call switch g...,67,0.001196,0.001196,0.001196,...,0.001196,0.001196,0.883028,0.786888,0.007027,0.000503,0.508450,0.885882,obscene,0.014286
28371,82451,jeezy,r.i.p.,2019,hip hop,remix killer alive remix thriller trap bitch s...,83,0.001012,0.075202,0.001012,...,0.001012,0.033995,0.828875,0.674794,0.015862,0.000000,0.475474,0.492477,obscene,0.014286

In [73]:
pandas.read_csv("LMS-DataStuff/movies-archive/credits.csv")

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [57]:
pandas.read_csv("LMS-DataStuff/movies-archive/keywords.csv")

           id                                           keywords
0         862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1        8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2       15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3       31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4       11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...
...       ...                                                ...
46414  439050             [{'id': 10703, 'name': 'tragic love'}]
46415  111109  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
46416   67758                                                 []
46417  227506                                                 []
46418  461257                                                 []

[46419 rows x 2 columns]

In [58]:
pandas.read_csv("LMS-DataStuff/movies-archive/links_small.csv")

      movieId   imdbId    tmdbId
0           1   114709     862.0
1           2   113497    8844.0
2           3   113228   15602.0
3           4   114885   31357.0
4           5   113041   11862.0
...       ...      ...       ...
9120   162672  3859980  402672.0
9121   163056  4262980  315011.0
9122   163949  2531318  391698.0
9123   164977    27660  137608.0
9124   164979  3447228  410803.0

[9125 rows x 3 columns]

In [59]:
pandas.read_csv("LMS-DataStuff/movies-archive/links.csv")

       movieId   imdbId    tmdbId
0            1   114709     862.0
1            2   113497    8844.0
2            3   113228   15602.0
3            4   114885   31357.0
4            5   113041   11862.0
...        ...      ...       ...
45838   176269  6209470  439050.0
45839   176271  2028550  111109.0
45840   176273   303758   67758.0
45841   176275     8536  227506.0
45842   176279  6980792  461257.0

[45843 rows x 3 columns]

In [60]:
pandas.read_csv("LMS-DataStuff/movies-archive/movies_metadata.csv")

/var/folders/f_/93v_b49109x0tkj367ph296m0000gp/T/ipykernel_36151/3095774179.py:1: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  pandas.read_csv("LMS-DataStuff/movies-archive/movies_metadata.csv")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [61]:
pandas.read_csv("LMS-DataStuff/movies-archive/ratings_small.csv")

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [62]:
pandas.read_csv("LMS-DataStuff/movies-archive/ratings.csv")

          userId  movieId  rating   timestamp
0              1      110     1.0  1425941529
1              1      147     4.5  1425942435
2              1      858     5.0  1425941523
3              1     1221     5.0  1425941546
4              1     1246     5.0  1425941556
...          ...      ...     ...         ...
26024284  270896    58559     5.0  1257031564
26024285  270896    60069     5.0  1257032032
26024286  270896    63082     4.5  1257031764
26024287  270896    64957     4.5  1257033990
26024288  270896    71878     2.0  1257031858

[26024289 rows x 4 columns]

In [53]:
pandas.read_csv("LMS-DataStuff/movies-archive/merge_preview.csv")

/var/folders/f_/93v_b49109x0tkj367ph296m0000gp/T/ipykernel_17120/2932089626.py:1: DtypeWarning: Columns (0: tmdb_id) have mixed types. Specify dtype option on import or set low_memory=False.
  pandas.read_csv("LMS-DataStuff/movies-archive/merge_preview.csv")

,movieId,tmdb_id,imdb_id,title,collection,overview,cast,crew,rating,genres,runtime,production_companies,release_date,spoken_languages,keywords
0,NaN,100,tt0120735,"Lock, Stock and Two Smoking Barrels",NaN,A card sharp and his unwillingly-enlisted frie...,"[{'cast_id': 12, 'character': 'Tom', 'credit_i...","[{'credit_id': '52fe4217c3a36847f80035c1', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",105.0,"[{'name': 'Handmade Films Ltd.', 'id': 146}, {...",1998-03-05,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 502, 'name': 'ambush'}, {'id': 567, 'n..."
1,2542.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,10000,tt0109747,La estrategia del caracol,NaN,A group of tenants living in an old house are ...,[],"[{'credit_id': '5375293cc3a3681ee90001ad', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",116.0,[{'name': 'Ministère de la Culture et de la Fr...,1993-12-25,"[{'iso_639_1': 'es', 'name': 'Español'}]","[{'id': 1253, 'name': 'roommate'}, {'id': 1499..."
3,68168.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,10001,tt0096486,Young Einstein,NaN,Albert Einstein is the son of a Tasmanian appl...,"[{'cast_id': 17, 'character': 'Albert Einstein...","[{'credit_id': '52fe43039251416c75000035', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 878, 'na...",91.0,"[{'name': 'Warner Bros.', 'id': 6194}]",1988-12-15,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 1815, 'name': 'atomic bomb'}, {'id': 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91026,NaN,99977.0,tt0079308,Hot Stuff,NaN,When a police department's burglary task force...,"[{'cast_id': 1, 'character': 'Ernie Fortunato'...","[{'credit_id': '52fe4a4a9251416c750e41d9', 'de...",False,"[{'id': 35, 'name': 'Comedy'}]",91.0,"[{'name': 'Rastar Pictures', 'id': 2070}]",1979-08-10,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'id': 6149, 'name': 'police'}, {'id': 7155, ..."
91027,117519.0,99977.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91028,NaN,9999.0,tt0499101,The Free Will,NaN,After nine years in psychiatric detention Theo...,"[{'cast_id': 17, 'character': 'Theo', 'credit_...","[{'credit_id': '52fe455bc3a36847f80c9a97', 'de...",False,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",163.0,"[{'name': 'Colonia Media', 'id': 1084}]",2006-08-23,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...","[{'id': 570, 'name': 'rape'}, {'id': 1591, 'na..."
91029,63645.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91030,142.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
pandas.read_csv("LMS-DataStuff/movies-archive/movies_data_part1.csv")

,movieId,tmdb_id,imdb_id,title,collection,overview,runtime,cast,crew,rating,genres,keywords,production_companies,release_date,spoken_languages
0,NaN,100,tt0120735,"Lock, Stock and Two Smoking Barrels",NaN,A card sharp and his unwillingly-enlisted frie...,105.0,"[{'cast_id': 12, 'character': 'Tom', 'credit_i...","[{'credit_id': '52fe4217c3a36847f80035c1', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...","[{'id': 502, 'name': 'ambush'}, {'id': 567, 'n...","[{'name': 'Handmade Films Ltd.', 'id': 146}, {...",1998-03-05,"[{'iso_639_1': 'en', 'name': 'English'}]"
1,2542.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,10000,tt0109747,La estrategia del caracol,NaN,A group of tenants living in an old house are ...,116.0,[],"[{'credit_id': '5375293cc3a3681ee90001ad', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 1253, 'name': 'roommate'}, {'id': 1499...",[{'name': 'Ministère de la Culture et de la Fr...,1993-12-25,"[{'iso_639_1': 'es', 'name': 'Español'}]"
3,68168.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,10001,tt0096486,Young Einstein,NaN,Albert Einstein is the son of a Tasmanian appl...,91.0,"[{'cast_id': 17, 'character': 'Albert Einstein...","[{'credit_id': '52fe43039251416c75000035', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 878, 'na...","[{'id': 1815, 'name': 'atomic bomb'}, {'id': 2...","[{'name': 'Warner Bros.', 'id': 6194}]",1988-12-15,"[{'iso_639_1': 'en', 'name': 'English'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45510,NaN,31395,tt0109376,"Car 54, Where Are You?",NaN,Brash NYC policeman Officer Gunther Toody is p...,89.0,"[{'cast_id': 8, 'character': 'Officer Gunther ...","[{'credit_id': '53b9f8e50e0a2676bf00a868', 'de...",False,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...","[{'id': 6149, 'name': 'police'}, {'id': 10988,...","[{'name': 'Orion Pictures', 'id': 41}]",1994-01-28,"[{'iso_639_1': 'en', 'name': 'English'}]"
45511,7189.0,31395.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45512,NaN,31396,tt0058311,Hercules Against the Moon Men,NaN,Hercules is summoned to oppose the evil Queen ...,90.0,"[{'cast_id': 1010, 'character': 'Maciste / Her...","[{'credit_id': '52fe447a9251416c91012179', 'de...",False,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...","[{'id': 305, 'name': 'moon'}, {'id': 2035, 'na...","[{'name': 'Nike Cinematografica', 'id': 15325}...",1964-06-27,"[{'iso_639_1': 'it', 'name': 'Italiano'}]"
45513,146491.0,31396.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45514,NaN,31397,tt0092532,Alien from L.A.,NaN,When her archaeologist father disappears on an...,87.0,"[{'cast_id': 4, 'character': 'Wanda Saknussemm...","[{'credit_id': '54a847aec3a3680c29002469', 'de...",False,"[{'id': 28, 'name': 'Action'}, {'id': 10751, '...","[{'id': 385, 'name': 'jules verne'}, {'id': 19...","[{'name': 'Cannon Group', 'id': 1444}, {'name'...",1988-01-01,"[{'iso_639_1': 'en', 'name': 'English'}]"

In [55]:
pandas.read_csv("LMS-DataStuff/movies-archive/movies_data_section1.csv")

,movieId,tmdb_id,imdb_id,title,collection,overview,runtime,cast,crew,rating,genres,keywords,production_companies,release_date,spoken_languages
0,NaN,100.0,tt0120735,"Lock, Stock and Two Smoking Barrels",NaN,A card sharp and his unwillingly-enlisted frie...,105.0,"[{'cast_id': 12, 'character': 'Tom', 'credit_i...","[{'credit_id': '52fe4217c3a36847f80035c1', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...","[{'id': 502, 'name': 'ambush'}, {'id': 567, 'n...","[{'name': 'Handmade Films Ltd.', 'id': 146}, {...",1998-03-05,"[{'iso_639_1': 'en', 'name': 'English'}]"
1,2542.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,10000.0,tt0109747,La estrategia del caracol,NaN,A group of tenants living in an old house are ...,116.0,[],"[{'credit_id': '5375293cc3a3681ee90001ad', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","[{'id': 1253, 'name': 'roommate'}, {'id': 1499...",[{'name': 'Ministère de la Culture et de la Fr...,1993-12-25,"[{'iso_639_1': 'es', 'name': 'Español'}]"
3,68168.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,10001.0,tt0096486,Young Einstein,NaN,Albert Einstein is the son of a Tasmanian appl...,91.0,"[{'cast_id': 17, 'character': 'Albert Einstein...","[{'credit_id': '52fe43039251416c75000035', 'de...",False,"[{'id': 35, 'name': 'Comedy'}, {'id': 878, 'na...","[{'id': 1815, 'name': 'atomic bomb'}, {'id': 2...","[{'name': 'Warner Bros.', 'id': 6194}]",1988-12-15,"[{'iso_639_1': 'en', 'name': 'English'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,NaN,19725.0,tt0103927,Carry On Columbus,"{'id': 37261, 'name': 'The Carry On Collection...",Christopher Columbus believes he can find an a...,91.0,"[{'cast_id': 4, 'character': 'Christopher Colu...","[{'credit_id': '52fe47ed9251416c750aa12f', 'de...",False,"[{'id': 35, 'name': 'Comedy'}]","[{'id': 658, 'name': 'sea'}, {'id': 3799, 'nam...","[{'name': 'Peter Rogers Productions', 'id': 10...",1992-10-02,"[{'iso_639_1': 'en', 'name': 'English'}]"
24996,139461.0,19725.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24997,NaN,19727.0,tt1203523,Streets of Blood,NaN,A police officer's partner has died during Hur...,95.0,"[{'cast_id': 1, 'character': 'Detective Andy D...","[{'credit_id': '52fe47ed9251416c750aa21f', 'de...",False,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",[],"[{'name': 'Nu Image Films', 'id': 925}, {'name...",2009-07-13,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso..."
24998,70064.0,19727.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24999,NaN,197276.0,tt2649274,The Ghost Army,NaN,"During World War II, a hand-picked group of Am...",68.0,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '5658dfc19251416dd50042ba', 'de...",False,"[{'id': 99, 'name': 'Documentary'}, {'id': 107...","[{'id': 1956, 'name': 'world war ii'}, {'id': ...","[{'name': 'Plate of Peas Productions', 'id': 5...",2013-05-26,"[{'iso_639_1': 'en', 'name': 'English'}]"

In [63]:
pandas.read_csv("LMS-DataStuff/trove-periodicals-data-main/periodical-issues.csv")

,id,title_id,title,description,date,url,pages,text_download_url
0,nla.obj-8447243,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Volume 1 Number 1,1916-11-10,https://nla.gov.au/nla.obj-8447243,48,https://trove.nla.gov.au/nla.obj-8447243/downl...
1,nla.obj-8452230,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Volume 1 Number 2,1916-12-20,https://nla.gov.au/nla.obj-8452230,40,https://trove.nla.gov.au/nla.obj-8452230/downl...
2,nla.obj-8458012,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Volume 1 Number 3,1917-01-19,https://nla.gov.au/nla.obj-8458012,40,https://trove.nla.gov.au/nla.obj-8458012/downl...
3,nla.obj-8465575,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Volume 1 Number 4,1917-02-19,https://nla.gov.au/nla.obj-8465575,40,https://trove.nla.gov.au/nla.obj-8465575/downl...
4,nla.obj-8469716,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Volume 1 Number 5,1917-03-09,https://nla.gov.au/nla.obj-8469716,36,https://trove.nla.gov.au/nla.obj-8469716/downl...
...,...,...,...,...,...,...,...,...
37010,nla.obj-490481414,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,21st (2012),2012-11-06,https://nla.gov.au/nla.obj-490481414,99,https://trove.nla.gov.au/nla.obj-490481414/dow...
37011,nla.obj-490492247,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,22nd (2013),2013-11-12,https://nla.gov.au/nla.obj-490492247,94,https://trove.nla.gov.au/nla.obj-490492247/dow...
37012,nla.obj-490512490,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,23rd (2014),2014-11-11,https://nla.gov.au/nla.obj-490512490,116,https://trove.nla.gov.au/nla.obj-490512490/dow...
37013,nla.obj-490513884,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,24th (2015),2015-11-11,https://nla.gov.au/nla.obj-490513884,122,https://trove.nla.gov.au/nla.obj-490513884/dow...
37014,nla.obj-490602519,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,25th (2016),2016-11-09,https://nla.gov.au/nla.obj-490602519,134,https://trove.nla.gov.au/nla.obj-490602519/dow...

In [3]:
pandas.read_csv("LMS-DataStuff/trove-periodicals-data-main/periodical-titles.csv")

,id,title,description,publisher,trove_url,download_text,issue_count,start_date,end_date,start_year,end_year,extent,place,issn,catalogue_url
0,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",NaN,Partridge & Love Ltd.,https://nla.gov.au/nla.obj-8423556,https://trove-journals.s3.ap-southeast-2.amazo...,13,1916-01-01,1917-10-20,1916.0,1917.0,1 v. ; ill. ; 25 cm.,NaN,NaN,https://nla.gov.au/nla.cat-vn377167
1,nla.obj-2998991958,"(Ross's) Hobart Town almanack, and Van Diemen'...",NaN,Printed by James Ross,https://nla.gov.au/nla.obj-2998991958,https://trove-journals.s3.ap-southeast-2.amazo...,1,1835-01-01,1835-01-01,1835.0,1835.0,2 volumes : illustrations ; 18 cm.,Tasmania,NaN,https://nla.gov.au/nla.cat-vn610781
2,nla.obj-2998997061,(Ross's) Van Diemen's Land annual and Hobart T...,NaN,Printed by James Ross,https://nla.gov.au/nla.obj-2998997061,https://trove-journals.s3.ap-southeast-2.amazo...,1,1834-01-01,1934-01-01,1934.0,1934.0,1 volumes : illustrations ; 18 cm.,Tasmania,NaN,https://nla.gov.au/nla.cat-vn2133206
3,nla.obj-15956697,14th Company magazine.,NaN,14th Company.,https://nla.gov.au/nla.obj-15956697,https://trove-journals.s3.ap-southeast-2.amazo...,1,0191-01-01,1918-06-14,1918.0,1918.0,v. ; 25 cm.,Australia,NaN,https://nla.gov.au/nla.cat-vn585007
4,nla.obj-250818955,20 favourite & war-time camp songs [music].,NaN,Sterling Music,https://nla.gov.au/nla.obj-250818955,https://trove-journals.s3.ap-southeast-2.amazo...,7,1940-01-01,NaN,NaN,NaN,7 v. of music ; 29 cm.,NaN,NaN,https://nla.gov.au/nla.cat-vn2926496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,nla.obj-54933471,[Acts].,NaN,Govt. Printer of the Northern Territory,https://nla.gov.au/nla.obj-54933471,https://trove-journals.s3.ap-southeast-2.amazo...,2,1978-01-01,1994-01-01,1983.0,1994.0,v. ; 25 cm.,Northern Territory,NaN,https://nla.gov.au/nla.cat-vn427257
904,nla.obj-3193629693,[Australian medical pamphlets].,NaN,NaN,https://nla.gov.au/nla.obj-3193629693,https://trove-journals.s3.ap-southeast-2.amazo...,1,1855-01-01,NaN,NaN,NaN,35 v. ; 21-32 cm,NaN,NaN,https://nla.gov.au/nla.cat-vn1716521
905,nla.obj-773155481,[Magazine],NaN,Daramalan College.,https://nla.gov.au/nla.obj-773155481,https://trove-journals.s3.ap-southeast-2.amazo...,58,1957-01-01,2017-01-01,1962.0,2017.0,v. : ill. ; 29 cm.,NaN,NaN,https://nla.gov.au/nla.cat-vn2643237
906,nla.obj-526663409,[Magazine],NaN,Northern Peninsula Area State College,https://nla.gov.au/nla.obj-526663409,https://trove-journals.s3.ap-southeast-2.amazo...,4,2005-01-01,2017-01-01,2007.0,2017.0,volumes : illustrations (some colour) ; 30 cm,Queensland,NaN,https://nla.gov.au/nla.cat-vn7083997
907,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,NaN,[New South Wales Coastal Conference],https://nla.gov.au/nla.obj-489106103,https://trove-journals.s3.ap-southeast-2.amazo...,12,2005-01-01,2016-11-09,2005.0,2016.0,online resource : illustrations,New South Wales,NaN,https://nla.gov.au/nla.cat-vn7422493

In [65]:
pandas.read_json("LMS-DataStuff/trove-periodicals-data-main/metadata.json")

,title,description,source,source_url,databases
periodicals,GLAM Workbench Data Explorer,Explore Trove's collection of digitised period...,trove-periodicals-data,https://github.com/GLAM-Workbench/trove-period...,"{'tables': {'titles': {'sort': 'title', 'searc..."

In [67]:
pandas.read_json("LMS-DataStuff/trove-periodicals-data-main/periodical-issues-schema.json")

                                              fields
0  {'name': 'id', 'type': 'string', 'description'...
1  {'name': 'title_id', 'type': 'string', 'descri...
2  {'name': 'title', 'type': 'string', 'descripti...
3  {'name': 'description', 'type': 'string', 'des...
4  {'name': 'date', 'type': 'date', 'description'...
5  {'name': 'url', 'type': 'string', 'description...
6  {'name': 'pages', 'type': 'integer', 'descript...
7  {'name': 'text_download_url', 'type': 'string'...

In [69]:
pandas.read_json("LMS-DataStuff/trove-periodicals-data-main/periodical-titles-schema.json")

                                               fields
0   {'name': 'id', 'type': 'string', 'description'...
1   {'name': 'title', 'type': 'string', 'descripti...
2   {'name': 'description', 'type': 'string', 'des...
3   {'name': 'publisher', 'type': 'string', 'descr...
4   {'name': 'trove_url', 'type': 'string', 'descr...
5   {'name': 'download_text', 'type': 'string', 'd...
6   {'name': 'issue_count', 'type': 'integer', 'de...
7   {'name': 'start_date', 'type': 'date', 'descri...
8   {'name': 'end_date', 'type': 'date', 'descript...
9   {'name': 'start_year', 'type': 'integer', 'des...
10  {'name': 'end_year', 'type': 'integer', 'descr...
11  {'name': 'extent', 'type': 'string', 'descript...
12  {'name': 'place', 'type': 'string', 'descripti...
13  {'name': 'issn', 'type': 'string', 'descriptio...
14  {'name': 'catalogue_url', 'type': 'string', 'd...

In [70]:
pandas.read_json("LMS-DataStuff/trove-periodicals-data-main/ro-crate-metadata.json")

,@context,@graph
0,https://w3id.org/ro/crate/1.1/context,"{'@id': './', '@type': 'Dataset', 'author': [{..."
1,https://w3id.org/ro/crate/1.1/context,"{'@id': 'ro-crate-metadata.json', '@type': 'Cr..."
2,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://github.com/GLAM-Workbench/tro...
3,https://w3id.org/ro/crate/1.1/context,"{'@id': 'titles-issues-added.ndjson', '@type':..."
4,https://w3id.org/ro/crate/1.1/context,"{'@id': 'periodical-titles.csv', '@type': ['Fi..."
5,https://w3id.org/ro/crate/1.1/context,"{'@id': 'periodical-issues.csv', '@type': ['Fi..."
6,https://w3id.org/ro/crate/1.1/context,"{'@id': 'periodicals.db', '@type': ['File', 'D..."
7,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://github.com/GLAM-Workbench/tro...
8,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://orcid.org/0000-0001-7956-4498...
9,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://github.com/GLAM-Workbench/tro...
10,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://github.com/GLAM-Workbench/tro...
11,https://w3id.org/ro/crate/1.1/context,"{'@id': 'https://spdx.org/licenses/MIT', '@typ..."
12,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://creativecommons.org/publicdom...
13,https://w3id.org/ro/crate/1.1/context,{'@id': 'http://rightsstatements.org/vocab/NKC...
14,https://w3id.org/ro/crate/1.1/context,{'@id': 'http://rightsstatements.org/vocab/CNE...
15,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://www.python.org/downloads/rele...
16,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://glam-workbench.net/trove-jour...
17,https://w3id.org/ro/crate/1.1/context,{'@id': '#periodicals-enrich-for-datasette_run...
18,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://glam-workbench.net/trove-jour...
19,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://glam-workbench.net/datasette-...
20,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://tdg.glam-workbench.net/other-...
21,https://w3id.org/ro/crate/1.1/context,{'@id': 'https://glam-workbench.net/trove-jour...
22,https://w3id.org/ro/crate/1.1/context,"{'@id': '#periodicals-from-api_run_0', '@type'..."
23,https://w3id.org/ro/crate/1.1/context,"{'@id': 'periodical-titles-schema.json', '@typ..."
24,https://w3id.org/ro/crate/1.1/context,"{'@id': 'periodical-issues-schema.json', '@typ..."

In [71]:
pandas.read_json("LMS-DataStuff/trove-periodicals-data-main/titles-issues-added.ndjson", lines=True)

,id,title,publisher,troveUrl,start_year,end_year,issue_count,unknown_dates,issues,new_issue_count,startDate,endDate,place,issn
0,nla.obj-244631375,"... musical cabinet, no. 1-37 by W.H. Glen & C...",W.H. Glen & Co.,https://nla.gov.au/nla.obj-244631375,NaN,NaN,0,2,"[{'id': 'nla.obj-244630361', 'date': '', 'desc...",2,NaN,NaN,NaN,NaN
1,nla.obj-243252799,"... musical magazine, No. 1-89 by Nicholson, [...",Nicholson & Co.; Nicholson & Ascherberg; some ...,https://nla.gov.au/nla.obj-243252799,NaN,NaN,0,2,"[{'id': 'nla.obj-242068940', 'date': '', 'desc...",2,NaN,NaN,NaN,NaN
2,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Partridge & Love Ltd.,https://nla.gov.au/nla.obj-8423556,1916.0,1917.0,13,0,"[{'id': 'nla.obj-8447243', 'date': '1916-11-10...",13,1916-01-01,1917-10-20,NaN,NaN
3,nla.obj-2998991958,"(Ross's) Hobart Town almanack, and Van Diemen'...",Printed by James Ross,https://nla.gov.au/nla.obj-2998991958,1835.0,1835.0,1,0,"[{'id': 'nla.obj-3041640304', 'date': '1835-01...",1,1835-01-01,1835-01-01,[Tasmania],NaN
4,nla.obj-2998997061,(Ross's) Van Diemen's Land annual and Hobart T...,Printed by James Ross,https://nla.gov.au/nla.obj-2998997061,1934.0,1934.0,1,0,"[{'id': 'nla.obj-3008849314', 'date': '1934-01...",1,1834-01-01,1934-01-01,[Tasmania],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,nla.obj-3095242188,Year book of the Royal Australian Institute of...,The Institute,https://nla.gov.au/nla.obj-3095242188,1938.0,1962.0,16,0,"[{'id': 'nla.obj-3105449544', 'date': '1938-01...",16,0193-01-01,1962-01-01,[Australia],NaN
945,nla.obj-3050325075,Yesterday & most of today.,C. William.,https://nla.gov.au/nla.obj-3050325075,1933.0,1934.0,9,0,"[{'id': 'nla.obj-3076569117', 'date': '1933-01...",9,1932-01-01,1934-03-01,NaN,NaN
946,nla.obj-3095030785,Your home in W.A.,Imperial Print,https://nla.gov.au/nla.obj-3095030785,1947.0,1948.0,7,0,"[{'id': 'nla.obj-3107051470', 'date': '1947-10...",7,1947-01-01,1948-05-01,NaN,NaN
947,nla.obj-60535517,Zhong xi jiao hui bao,Society for the Diffusion of Christian and Gen...,https://nla.gov.au/nla.obj-60535517,NaN,NaN,0,24,"[{'id': 'nla.obj-60535525', 'date': '', 'descr...",24,1891-01-01,NaN,NaN,NaN
948,nla.obj-60418801,Zhong xi wen jian lu.,s.n.],https://nla.gov.au/nla.obj-60418801,NaN,NaN,0,32,"[{'id': 'nla.obj-60418817', 'date': '', 'descr...",32,1872-01-01,NaN,NaN,NaN

In [23]:
pandas.read_csv("LMS-DataStuff/issue_unmerged.csv")

,id,issue_id,issue_number,date_published,page_count
0,nla.obj-8423556,nla.obj-8447243,Volume 1 Number 1,1916-11-10,48
1,nla.obj-8423556,nla.obj-8452230,Volume 1 Number 2,1916-12-20,40
2,nla.obj-8423556,nla.obj-8458012,Volume 1 Number 3,1917-01-19,40
3,nla.obj-8423556,nla.obj-8465575,Volume 1 Number 4,1917-02-19,40
4,nla.obj-8423556,nla.obj-8469716,Volume 1 Number 5,1917-03-09,36
...,...,...,...,...,...
37010,nla.obj-489106103,nla.obj-490481414,21st (2012),2012-11-06,99
37011,nla.obj-489106103,nla.obj-490492247,22nd (2013),2013-11-12,94
37012,nla.obj-489106103,nla.obj-490512490,23rd (2014),2014-11-11,116
37013,nla.obj-489106103,nla.obj-490513884,24th (2015),2015-11-11,122
37014,nla.obj-489106103,nla.obj-490602519,25th (2016),2016-11-09,134

In [22]:
pandas.read_csv("LMS-DataStuff/titles_unmerged.csv")

,id,title,publisher,trove_url,issue_count,start_date,end_date,start_year,end_year
0,nla.obj-8423556,"""Coo-ee!"" : the journal of the Bishops Knoll H...",Partridge & Love Ltd.,https://nla.gov.au/nla.obj-8423556,13,1916-01-01,1917-10-20,1916.0,1917.0
1,nla.obj-2998991958,"(Ross's) Hobart Town almanack, and Van Diemen'...",Printed by James Ross,https://nla.gov.au/nla.obj-2998991958,1,1835-01-01,1835-01-01,1835.0,1835.0
2,nla.obj-2998997061,(Ross's) Van Diemen's Land annual and Hobart T...,Printed by James Ross,https://nla.gov.au/nla.obj-2998997061,1,1834-01-01,1934-01-01,1934.0,1934.0
3,nla.obj-15956697,14th Company magazine.,14th Company.,https://nla.gov.au/nla.obj-15956697,1,0191-01-01,1918-06-14,1918.0,1918.0
4,nla.obj-250818955,20 favourite & war-time camp songs [music].,Sterling Music,https://nla.gov.au/nla.obj-250818955,7,1940-01-01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
903,nla.obj-54933471,[Acts].,Govt. Printer of the Northern Territory,https://nla.gov.au/nla.obj-54933471,2,1978-01-01,1994-01-01,1983.0,1994.0
904,nla.obj-3193629693,[Australian medical pamphlets].,NaN,https://nla.gov.au/nla.obj-3193629693,1,1855-01-01,NaN,NaN,NaN
905,nla.obj-773155481,[Magazine],Daramalan College.,https://nla.gov.au/nla.obj-773155481,58,1957-01-01,2017-01-01,1962.0,2017.0
906,nla.obj-526663409,[Magazine],Northern Peninsula Area State College,https://nla.gov.au/nla.obj-526663409,4,2005-01-01,2017-01-01,2007.0,2017.0
907,nla.obj-489106103,[Program &] abstracts [book] : [NSW Coastal Co...,[New South Wales Coastal Conference],https://nla.gov.au/nla.obj-489106103,12,2005-01-01,2016-11-09,2005.0,2016.0

In [24]:
pandas.read_csv("LMS-DataStuff/periodicals_issues_insert.csv")

                      id                                             insert
0        nla.obj-8423556  [{'issue_id': 'nla.obj-8447243', 'issue_number...
1        nla.obj-8423556  [{'issue_id': 'nla.obj-8452230', 'issue_number...
2        nla.obj-8423556  [{'issue_id': 'nla.obj-8458012', 'issue_number...
3        nla.obj-8423556  [{'issue_id': 'nla.obj-8465575', 'issue_number...
4        nla.obj-8423556  [{'issue_id': 'nla.obj-8469716', 'issue_number...
...                  ...                                                ...
37010  nla.obj-489106103  [{'issue_id': 'nla.obj-490481414', 'issue_numb...
37011  nla.obj-489106103  [{'issue_id': 'nla.obj-490492247', 'issue_numb...
37012  nla.obj-489106103  [{'issue_id': 'nla.obj-490512490', 'issue_numb...
37013  nla.obj-489106103  [{'issue_id': 'nla.obj-490513884', 'issue_numb...
37014  nla.obj-489106103  [{'issue_id': 'nla.obj-490602519', 'issue_numb...

[37015 rows x 2 columns]

In [27]:
pandas.read_csv("LMS-DataStuff/periodicals_merged.csv")

,id,title,publisher,trove_url,issue_count,issue data,start_date,end_date,start_year,end_year
0,nla.obj-1037567,Anzac bulletin : issued to members of the Aust...,Published by the authority of the High Commiss...,https://nla.gov.au/nla.obj-1037567,205.0,"[{'issue_id': 'nla.obj-31982495', 'issue_numbe...",1916-01-01,NaN,1916.0,2014.0
1,nla.obj-1037567,Anzac bulletin : issued to members of the Aust...,Published by the authority of the High Commiss...,https://nla.gov.au/nla.obj-1037567,205.0,"[{'issue_id': 'nla.obj-50254824', 'issue_numbe...",1916-01-01,NaN,1916.0,2014.0
2,nla.obj-1037567,Anzac bulletin : issued to members of the Aust...,Published by the authority of the High Commiss...,https://nla.gov.au/nla.obj-1037567,205.0,"[{'issue_id': 'nla.obj-61053849', 'issue_numbe...",1916-01-01,NaN,1916.0,2014.0
3,nla.obj-1037567,Anzac bulletin : issued to members of the Aust...,Published by the authority of the High Commiss...,https://nla.gov.au/nla.obj-1037567,205.0,"[{'issue_id': 'nla.obj-2084228', 'issue_number...",1916-01-01,NaN,1916.0,2014.0
4,nla.obj-1037567,Anzac bulletin : issued to members of the Aust...,Published by the authority of the High Commiss...,https://nla.gov.au/nla.obj-1037567,205.0,"[{'issue_id': 'nla.obj-2084709', 'issue_number...",1916-01-01,NaN,1916.0,2014.0
...,...,...,...,...,...,...,...,...,...,...
37118,nla.obj-969917508,Portal.,Brisbane Boys' College.,https://nla.gov.au/nla.obj-969917508,23.0,"[{'issue_id': 'nla.obj-1560772412', 'issue_num...",1916-01-01,1953-12-01,1931.0,1953.0
37119,nla.obj-969917508,Portal.,Brisbane Boys' College.,https://nla.gov.au/nla.obj-969917508,23.0,"[{'issue_id': 'nla.obj-1563366828', 'issue_num...",1916-01-01,1953-12-01,1931.0,1953.0
37120,nla.obj-971558208,The progress of demobilisation and re-establis...,Ministry of Post-War Reconstruction,https://nla.gov.au/nla.obj-971558208,3.0,"[{'issue_id': 'nla.obj-1112778730', 'issue_num...",1946-01-01,1946-02-28,1946.0,1946.0
37121,nla.obj-971558208,The progress of demobilisation and re-establis...,Ministry of Post-War Reconstruction,https://nla.gov.au/nla.obj-971558208,3.0,"[{'issue_id': 'nla.obj-1112803981', 'issue_num...",1946-01-01,1946-02-28,1946.0,1946.0
37122,nla.obj-971558208,The progress of demobilisation and re-establis...,Ministry of Post-War Reconstruction,https://nla.gov.au/nla.obj-971558208,3.0,"[{'issue_id': 'nla.obj-1036620047', 'issue_num...",1946-01-01,1946-02-28,1946.0,1946.0

In [32]:
pandas.read_csv("LMS-DataStuff/books_deduped.csv")

,Text#,Type,Issued,Title,Language,Authors,Subjects,LoCC,Bookshelves
0,1,Text,1971-12-01,The Declaration of Independence of the United ...,en,"Jefferson, Thomas, 1743-1826","United States -- History -- Revolution, 1775-1...",E201; JK,Politics; American Revolutionary War; United S...
1,2,Text,1972-12-01,The United States Bill of Rights\r\nThe Ten Or...,en,United States,Civil rights -- United States -- Sources; Unit...,JK; KF,Politics; American Revolutionary War; United S...
2,3,Text,1973-11-01,John F. Kennedy's Inaugural Address,en,"Kennedy, John F. (John Fitzgerald), 1917-1963",United States -- Foreign relations -- 1961-196...,E838,Browsing: History - American; Browsing: Politics
3,4,Text,1973-11-01,Lincoln's Gettysburg Address\r\nGiven November...,en,"Lincoln, Abraham, 1809-1865",Consecration of cemeteries -- Pennsylvania -- ...,E456,US Civil War; Browsing: History - American; Br...
4,5,Text,1975-12-01,The United States Constitution,en,United States,United States -- Politics and government -- 17...,JK; KF,United States; Politics; American Revolutionar...
...,...,...,...,...,...,...,...,...,...
64780,76310,Text,2025-06-15,Cindrulino,eo,"Milho, L.",NaN,NaN,NaN
64781,76311,Text,2025-06-15,The book of the cat,en,"Simpson, Frances",NaN,NaN,NaN
64782,76312,Text,2025-06-15,Viimeinen tsaaritar,fi,"Poljakov, V.",NaN,NaN,NaN
64783,76313,Text,2025-06-15,Voimatonta väkeä,fi,"Malmberg, Aino, 1865-1933",NaN,NaN,NaN
64784,76314,Text,2025-06-15,Genius rewarded,en,"Scott, John A.",NaN,NaN,NaN